# Generated by Django 5.2.7 on 2025-11-01 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=7)),
                ('tipo_instrumento', models.CharField(choices=[('Factura', 'Factura'), ('Boleta', 'Boleta'), ('Nota de crédito', 'Nota de crédito'), ('Otro', 'Otro')], max_length=30)),
                ('folio', models.CharField(max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado_validacion', models.CharField(choices=[('Válida', 'Válida'), ('Con advertencias', 'Con advertencias'), ('Rechazada', 'Rechazada')], max_length=30)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rut'], name='api_calific_rut_e535b4_idx'), models.Index(fields=['periodo'], name='api_calific_periodo_ac7a0d_idx'), models.Index(fields=['tipo_instrumento'], name='api_calific_tipo_in_3a9349_idx'), models.Index(fields=['estado_validacion'], name='api_calific_estado__f8ebdd_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.role')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
