# Generated by Django 5.2.7 on 2025-11-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('clp_per_unit', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
            options={
                'verbose_name': 'Tipo de cambio',
                'verbose_name_plural': 'Tipos de cambio',
            },
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
