# Generated by Django 5.2.7 on 2025-11-02 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fxrate_delete_calificacion_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fxrate',
            options={},
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=7)),
                ('tipo_instrumento', models.CharField(max_length=50)),
                ('folio', models.CharField(max_length=30)),
                ('monto', models.IntegerField()),
                ('estado_validacion', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['rut'], name='api_calific_rut_e535b4_idx'), models.Index(fields=['periodo'], name='api_calific_periodo_ac7a0d_idx'), models.Index(fields=['tipo_instrumento'], name='api_calific_tipo_in_3a9349_idx'), models.Index(fields=['estado_validacion'], name='api_calific_estado__f8ebdd_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.role')),
            ],
        ),
    ]
