# Generated by Django 5.2.6 on 2025-11-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='moneda',
            field=models.CharField(choices=[('CLP', 'CLP'), ('COP', 'COP'), ('PEN', 'PEN'), ('USD', 'USD')], default='CLP', max_length=3),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['moneda'], name='api_calific_moneda_321f97_idx'),
        ),
    ]
